### PR TITLE
Update ForceTimeGraphs.py to include correct path for data

### PR DESCRIPTION
**Pull request by DerenDesign**

### CODE REVIEW

**Review by Nishk04 — COMMENTED** [review]
For some reason, when I test it with the path you changed, it doesn't seem to work on my end. @allison-lane Could you try the path I had and the path Deren wrote because I believe we have the data file in the data folder so I'm not sure why it doesn't work for me and why the path I wrote doesn't work for him. Could you check which path works for you?

**Comment by allison-lane** [comment]
I'm not familiar with flask but I would guess this has to do with the line
```
@app.route('/graph')
```
because the error we're getting is /graph not found. @DerenDesign  Try playing around with that path.

**Comment by Nishk04** [comment]
@allison-lane Which path did you try? I don't think it's with that line because the button that takes you to the graph only changes the URL to '/graph' and then it accesses the file in the ForceTimeGraphs.py. I don't understand why the path I have or the path Deren has causes problems because they both seem correct. For me, the error I get when I try Deren's path is the line below. 
This is the line that I think might be causing the problems: 
df = pd.read_csv('Prepare2Play-Learning-Experience-main/data/SM_SbS_02_Raw_Data - SM_SoftballSwing_Trial2_Raw_Data.csv')

**Comment by DerenDesign** [comment]
@Nishk04 I deleted the pull request because I was able to run the code you wrote for the path for the data of the .csv file. I just tried it again and the program ran so it should be fine.

**Comment by DerenDesign** [comment]
@Nishk04 Also, we need to add under the readme that the user needs to do "pip install pandas and pip install flask" to install the proper python packages.

**Comment by Nishk04** [comment]
@DerenDesign Yeah you're right, we need to add instructions on what to install and anything else that may be important.

**Pull request closed without merging**
